export const demoDistricts = [
  { id: 'canary-falls-usd', name: 'Canary Falls Unified School District' },
];

export const demoQueries = [
  { id: 'demo-q-1', query_text: '"Canary Falls Unified School District" community programs', district_id: 'canary-falls-usd', district_name: 'Canary Falls Unified School District', geo_city: 'Canary Falls', geo_state: 'Demo State', geo_zip: '00000', channels: 'news', active: true, created_at: '2026-05-01' },
  { id: 'demo-q-2', query_text: '"Beacon Ridge High" family engagement', district_id: 'canary-falls-usd', district_name: 'Canary Falls Unified School District', geo_city: 'Canary Falls', geo_state: 'Demo State', geo_zip: '00000', channels: 'news', active: true, created_at: '2026-05-01' },
  { id: 'demo-q-3', query_text: 'Beacon Ridge High student achievement social', district_id: 'canary-falls-usd', district_name: 'Canary Falls Unified School District', geo_city: 'Canary Falls', geo_state: 'Demo State', geo_zip: '00000', channels: 'social', active: true, created_at: '2026-05-03' },
  { id: 'demo-q-4', query_text: 'Canary Falls Unified School District FAFSA graduation', district_id: 'canary-falls-usd', district_name: 'Canary Falls Unified School District', geo_city: 'Canary Falls', geo_state: 'Demo State', geo_zip: '00000', channels: 'all', active: true, created_at: '2026-05-05' },
  { id: 'demo-q-5', query_text: 'Canary Falls lookalike district validation examples', district_id: 'canary-falls-usd', district_name: 'Canary Falls Unified School District', geo_city: '', geo_state: '', geo_zip: '', channels: 'news', active: true, created_at: '2026-05-06' },
  { id: 'demo-q-6', query_text: 'Beacon Ridge High lockdown safety communication', district_id: 'canary-falls-usd', district_name: 'Canary Falls Unified School District', geo_city: 'Canary Falls', geo_state: 'Demo State', geo_zip: '00000', channels: 'news', active: true, created_at: '2026-06-11' },
];

export const demoArticles = [
  {
    id: 'demo-001', date: '2026-06-10', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Education Daily',
    headline: 'Beacon Ridge High School expands bilingual family resource nights for incoming freshmen',
    summary: 'Beacon Ridge High School announced a monthly evening series for incoming freshmen families, with translation support, counseling staff, and campus tours focused on easing the ninth-grade transition.',
    link: 'https://example.com/demo/beacon-ridge-family-resource-nights', canary_score: 8.7,
    tags: ['Family Engagement', 'Enrollment', 'Student Support'], notes: 'Good story to amplify before freshman orientation.', is_earned_media: true, is_perched: false,
    innovation_reason: 'Shows proactive family engagement and multilingual access, both aligned with community-trust messaging.',
    recommendation: 'Share as a short social post and add a principal quote about belonging before the first event. Include the registration link and translation availability.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-016', date: '2026-06-10', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Safety Bulletin Demo',
    headline: 'Beacon Ridge High enters brief lockdown after police activity reported near campus',
    summary: 'Beacon Ridge High School was placed in a brief precautionary lockdown after police activity was reported several blocks from campus. No students or staff were injured, and the school resumed normal operations after law enforcement cleared the area.',
    link: 'https://example.com/demo/brief-lockdown-safety-update', canary_score: 2.7,
    tags: ['Safety', 'Crisis Response', 'Family Communication'], notes: 'Full-recommendation demo scenario adapted from Lesley\'s lockdown example direction.', is_earned_media: false, is_perched: false,
    innovation_reason: 'High-sensitivity safety item where speed, clarity, and empathy matter more than amplification.',
    recommendation: 'Immediate response: Publish a concise safety update across parent email, SMS, website alerts, and social channels confirming the lockdown timeline, that students and staff are safe, and that normal operations have resumed. Audience focus: Lead with families and staff first, then prepare a short media holding statement so public coverage does not outpace district communication. Message guidance: Avoid speculation about the off-campus incident; explain what the school did, when law enforcement cleared the scene, and where families can get follow-up information. Follow-up: Send a second message by end of day with counseling/support resources, principal contact information, and any procedural reminders for reunification or emergency notifications.',
    source_query: 'Beacon Ridge High School Canary Falls lockdown safety communication',
  },
  {
    id: 'demo-002', date: '2026-06-09', district_id: 'canary-falls-usd', source_type: 'facebook', source: 'Beacon Ridge High School Facebook',
    headline: 'Photos: Beacon Ridge High robotics students demonstrate solar-powered design at community showcase',
    summary: 'The school posted photos from a student showcase where robotics students presented solar-powered prototypes to local business partners and family members.',
    link: 'https://example.com/demo/robotics-showcase', canary_score: 9.2,
    tags: ['STEM', 'Student Achievement', 'Community Partners'], notes: null, is_earned_media: true, is_perched: false,
    innovation_reason: 'Connects student learning to locally relevant energy themes and external partner validation.',
    recommendation: 'Repurpose the strongest photo into a district LinkedIn post and pitch a short student-innovation feature to local media.',
    source_query: 'Beacon Ridge High Bobcats Canary Falls athletics',
  },
  {
    id: 'demo-003', date: '2026-06-08', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Neighborhood Tribune',
    headline: 'Neighbors ask for more notice around Beacon Ridge High summer parking lot construction',
    summary: 'A neighborhood story noted confusion around temporary parking restrictions tied to construction on the Beacon Ridge High campus. Residents said signs appeared after work had already started.',
    link: 'https://example.com/demo/parking-construction-notice', canary_score: 3.4,
    tags: ['Facilities', 'Community Concern', 'Operations'], notes: 'Demo high-risk item: needs fast operational follow-up.', is_earned_media: false, is_perched: false,
    innovation_reason: 'Not an innovation story; this is a preventable trust-friction issue around communication timing.',
    recommendation: 'Post a same-day construction update with timeline, map, and contact email. Ask the principal or operations lead to acknowledge the notice gap and explain what changes next week.',
    source_query: '"Beacon Ridge High" "Canary Falls Unified"',
  },
  {
    id: 'demo-004', date: '2026-06-07', district_id: 'canary-falls-usd', source_type: 'instagram', source: 'Beacon Ridge High Instagram',
    headline: 'Senior spotlight series celebrates first-generation college-bound students',
    summary: 'A social series highlighted seniors who will be the first in their families to attend college, including quotes about counselors, teachers, and family support.',
    link: 'https://example.com/demo/senior-spotlight', canary_score: 9.0,
    tags: ['Graduation', 'College Readiness', 'Equity'], notes: null, is_earned_media: true, is_perched: false,
    innovation_reason: 'Humanizes college readiness outcomes and gives families a concrete view of student support systems.',
    recommendation: 'Bundle the series into a web recap and ask alumni to comment with encouragement. Consider a follow-up story on FAFSA supports.',
    source_query: 'Beacon Ridge High School Canary Falls FAFSA graduation',
  },
  {
    id: 'demo-005', date: '2026-06-06', district_id: 'canary-falls-usd', source_type: 'twitter', source: 'Canary Falls Transit Updates',
    headline: 'Morning bus detour near Beacon Avenue expected to affect Beacon Ridge High arrival traffic',
    summary: 'A public transit account announced a morning detour near campus. The post did not mention the school directly but could affect student arrival and family drop-off.',
    link: 'https://example.com/demo/bus-detour', canary_score: 5.8,
    tags: ['Transportation', 'Operations'], notes: null, is_earned_media: false, is_perched: false,
    innovation_reason: 'Operationally relevant external mention; not reputation positive or negative on its own.',
    recommendation: 'Add a temporary arrival notice to parent channels and remind families of alternate drop-off routes for the affected morning.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-006', date: '2026-06-04', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Sports Wire',
    headline: 'Beacon Ridge High track athletes qualify for state finals after standout relay performance',
    summary: 'Beacon Ridge High student athletes qualified for state finals after a season-best relay performance, with coaches praising academic eligibility and teamwork.',
    link: 'https://example.com/demo/track-state-finals', canary_score: 8.5,
    tags: ['Athletics', 'Student Achievement'], notes: null, is_earned_media: true, is_perched: false,
    innovation_reason: 'Positive student success story with academic eligibility angle beyond athletics.',
    recommendation: 'Celebrate the students, mention classroom eligibility expectations, and tag the athletics program before the state meet.',
    source_query: 'Beacon Ridge High Bobcats Canary Falls athletics',
  },
  {
    id: 'demo-007', date: '2026-06-02', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Civic Watch',
    headline: 'Board agenda includes security-camera upgrade request for Beacon Ridge High campus',
    summary: 'A civic agenda preview noted an upcoming vote on campus security-camera upgrades, with parent comments split between safety benefits and privacy concerns.',
    link: 'https://example.com/demo/security-camera-agenda', canary_score: 4.2,
    tags: ['Safety', 'Board Meeting', 'Parent Concern'], notes: 'Potential FAQ before board meeting.', is_earned_media: false, is_perched: false,
    innovation_reason: 'Technology upgrade intersects with privacy concerns, making proactive explanation important.',
    recommendation: 'Publish a short FAQ before the vote: what changes, who can access footage, retention policy, and how the upgrade supports student safety.',
    source_query: '"Beacon Ridge High" "Canary Falls Unified"',
  },
  {
    id: 'demo-008', date: '2026-05-31', district_id: 'canary-falls-usd', source_type: 'facebook', source: 'Beacon Ridge High Facebook',
    headline: 'Video recap: Beacon Ridge High culinary students prepare meals for community resource fair',
    summary: 'A district video showed culinary students preparing meals for a resource fair serving families near the Beacon Ridge High campus.',
    link: 'https://example.com/demo/culinary-resource-fair', canary_score: 8.8,
    tags: ['CTE', 'Community Service', 'Video'], notes: null, is_earned_media: true, is_perched: false,
    innovation_reason: 'Demonstrates career-connected learning and community contribution in a visual format.',
    recommendation: 'Clip a 20-second student quote for social and connect the post to CTE enrollment before course selection closes.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-009', date: '2026-05-29', district_id: 'canary-falls-usd', source_type: 'news', source: 'Valley Parent Forum',
    headline: 'Parents trade tips online after Beacon Ridge High posts summer credit-recovery schedule',
    summary: 'A parent forum thread shared questions about summer credit recovery, including how families should confirm transportation, meals, and course timing.',
    link: 'https://example.com/demo/credit-recovery-questions', canary_score: 6.2,
    tags: ['Summer School', 'Family Questions'], notes: null, is_earned_media: false, is_perched: false,
    innovation_reason: 'Shows where public confusion exists after an official announcement.',
    recommendation: 'Update the summer school page with a simple FAQ covering transportation, meals, course start times, and who to contact.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-010', date: '2026-05-27', district_id: 'canary-falls-usd', source_type: 'instagram', source: 'Beacon Ridge High Instagram',
    headline: 'Beacon Ridge High mariachi ensemble invited to perform at downtown arts festival',
    summary: 'The school celebrated its mariachi ensemble being invited to a downtown arts festival, highlighting student practice and cultural pride.',
    link: 'https://example.com/demo/mariachi-festival', canary_score: 9.4,
    tags: ['Arts', 'Culture', 'Student Achievement'], notes: 'Strong earned media pitch opportunity.', is_earned_media: true, is_perched: false,
    innovation_reason: 'Strongly aligns with culture, belonging, and community visibility.',
    recommendation: 'Pitch a photo-friendly arts feature to local media and invite families to attend. Capture student quotes before the event.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-011', date: '2026-05-24', district_id: 'canary-falls-usd', source_type: 'news', source: 'Demo Filter Log',
    headline: 'Filtered out: Beacon Ridge High in another state wins baseball championship',
    summary: 'This sample illustrates a lookalike mention that would be filtered out by geo-validation because the article is about a Beacon Ridge High in a different community.',
    link: 'https://example.com/demo/filtered-lookalike', canary_score: 1.8,
    tags: ['Geo Validation', 'Filtered Example'], notes: 'Use this to explain why fake/demo data includes a wrong-district example.', is_earned_media: false, is_perched: false,
    innovation_reason: 'Demonstrates the product differentiator: matching the school name is not enough without local context.',
    recommendation: 'No action. Canary would suppress or flag this as a wrong-district collision before it reaches the live feed.',
    source_query: 'Beacon Ridge High School wrong district examples',
  },
  {
    id: 'demo-012', date: '2026-05-22', district_id: 'canary-falls-usd', source_type: 'facebook', source: 'Beacon Ridge High PTO Facebook',
    headline: 'PTO asks families to donate water bottles ahead of excessive heat advisory',
    summary: 'The PTO posted a call for water bottle donations as temperatures rise, with comments from families asking whether outdoor practices will be adjusted.',
    link: 'https://example.com/demo/heat-water-bottles', canary_score: 5.1,
    tags: ['Weather', 'Student Safety', 'Family Questions'], notes: null, is_earned_media: false, is_perched: false,
    innovation_reason: 'Local operational context that can become reputational if families perceive gaps in heat planning.',
    recommendation: 'Coordinate one schoolwide heat-safety message with athletics and operations: water access, practice adjustments, and nurse contact information.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-013', date: '2026-05-20', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Business Journal Demo',
    headline: 'Local tech nonprofit funds after-school coding lab at Beacon Ridge High',
    summary: 'A technology nonprofit announced support for an after-school coding lab at Beacon Ridge High, including donated equipment and mentor hours from Canary Falls employers.',
    link: 'https://example.com/demo/coding-lab', canary_score: 9.1,
    tags: ['STEM', 'Partnerships', 'CTE'], notes: null, is_earned_media: true, is_perched: false,
    innovation_reason: 'High-value partnership story connecting workforce readiness with measurable student access.',
    recommendation: 'Thank the partner publicly, capture student participation numbers, and develop a short case study for prospective families and donors.',
    source_query: '"Beacon Ridge High" "Canary Falls Unified"',
  },
  {
    id: 'demo-014', date: '2026-05-18', district_id: 'canary-falls-usd', source_type: 'twitter', source: 'Local Reporter Demo Account',
    headline: 'Reporter asks for family perspectives on Beacon Ridge High grading-policy pilot',
    summary: 'A local reporter posted a request for families willing to discuss the school grading-policy pilot, signaling possible coverage before the district has framed the issue.',
    link: 'https://example.com/demo/grading-policy-reporter', canary_score: 4.8,
    tags: ['Policy', 'Media Inquiry', 'Potential Risk'], notes: 'Good example of early warning before article publishes.', is_earned_media: false, is_perched: false,
    innovation_reason: 'A media-query signal lets communications shape context before public coverage lands.',
    recommendation: 'Prepare background points on why the pilot exists, how success is measured, and where families can give feedback. Offer an administrator interview.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
  {
    id: 'demo-015', date: '2026-05-15', district_id: 'canary-falls-usd', source_type: 'news', source: 'Canary Falls Arts Calendar',
    headline: 'Beacon Ridge High students unveil mural honoring neighborhood history',
    summary: 'Students unveiled a campus mural created with local artists and community elders, connecting student art to neighborhood history.',
    link: 'https://example.com/demo/neighborhood-mural', canary_score: 8.9,
    tags: ['Arts', 'Community', 'Student Voice'], notes: null, is_earned_media: true, is_perched: false,
    innovation_reason: 'Strong student-voice and community-trust narrative with visual assets.',
    recommendation: 'Create a carousel post with student artist quotes and invite community partners to share the story.',
    source_query: '"Beacon Ridge High School" Canary Falls',
  },
];
