// Mock data based on what we observed in the Looker Studio dashboard
// This will be replaced with real Supabase queries once API keys are provided

export const mockArticles = [
  {
    id: 1,
    date: '2026-04-02',
    headline: 'Miles College Names Dr. Kesha James as Dean of Online Learning and Academic Affairs Data Manager',
    summary: 'Miles College has appointed Dr. Kesha James as the Dean of Online Learning and Academic Affairs Data Manager, bringing over 30 years of experience in education and a focus on innovation and digital learning.',
    link: 'https://www.miles.edu/news/miles-college-names-dr-kesha-james-dean-online-learning-and-academic-affairs-data-manager',
    notes: null,
    canary_score: 9.1,
    source_category: 'News',
    perch_tag: 'Higher Education',
  },
  {
    id: 2,
    date: '2026-03-22',
    headline: 'We love our community partner @BessemerPoliceD epartment! Thank you for supporting our efforts and loving us!',
    summary: 'The district expresses gratitude towards the Bessemer Police Department for their support and partnership.',
    link: 'https://www.facebook.com/BCStigers/posts',
    notes: null,
    canary_score: 8.65,
    source_category: 'Social Media',
    perch_tag: 'Community',
  },
  {
    id: 3,
    date: '2026-03-21',
    headline: 'Attendance is Important! Showing up every day makes a BIG difference!',
    summary: 'The post emphasizes the importance of attendance and celebrates students who achieved perfect attendance in January and February.',
    link: 'https://www.instagram.com/p/DWIIouJk2kl/',
    notes: 'Testing this right now',
    canary_score: 8.65,
    source_category: 'Social Media',
    perch_tag: 'Attendance',
  },
  {
    id: 4,
    date: '2026-03-18',
    headline: 'Who knew engineering could be this lucky? 🍀 Our Pre-K class turned into a team of master trap-builders today!',
    summary: 'Pre-K students at Bessemer City Schools engaged in a creative engineering project to build traps for a leprechaun.',
    link: 'https://www.instagram.com/p/DWAkp-6jl8g/',
    notes: null,
    canary_score: 8.65,
    source_category: 'Social Media',
    perch_tag: 'STEM',
  },
  {
    id: 5,
    date: '2026-03-13',
    headline: 'Today we celebrated these STAR students for perfect attendance and most improved.',
    summary: 'Today we celebrated STAR students for perfect attendance and most improved, with sweet treats and cash prizes. Special thanks to the staff who organized the event.',
    link: 'https://www.tiktok.com/@bcmsbessemer/video/761684',
    notes: null,
    canary_score: 8.65,
    source_category: 'Social Media',
    perch_tag: 'Attendance',
  },
  {
    id: 6,
    date: '2026-03-10',
    headline: 'Board of Education Approves New STEM Curriculum for Elementary Schools',
    summary: 'Bessemer City Board of Education voted unanimously to approve a modernized STEM curriculum that will be implemented across all elementary schools starting Fall 2026.',
    link: 'https://www.bessemer.k12.al.us/news/stem-curriculum',
    notes: 'Important policy decision - track follow-up coverage',
    canary_score: 9.2,
    source_category: 'News',
    perch_tag: 'Policy',
  },
  {
    id: 7,
    date: '2026-03-08',
    headline: 'Bessemer City Schools Report Record-Breaking Enrollment Numbers',
    summary: 'The district has seen a 12% increase in enrollment, marking the highest numbers in over a decade, attributed to new programs and community engagement.',
    link: 'https://www.al.com/education/bessemer-schools-enrollment',
    notes: null,
    canary_score: 9.5,
    source_category: 'News',
    perch_tag: 'Enrollment',
  },
  {
    id: 8,
    date: '2026-03-05',
    headline: 'Student Athletes Recognized at Annual Sports Banquet',
    summary: 'Over 200 student athletes were honored at the annual Bessemer City Schools Sports Banquet for their achievements in academics and athletics.',
    link: 'https://www.facebook.com/BCStigers/posts/sports-banquet',
    notes: null,
    canary_score: 7.8,
    source_category: 'Social Media',
    perch_tag: 'Athletics',
  },
  {
    id: 9,
    date: '2026-03-01',
    headline: 'New Partnership with Local Business to Fund After-School Programs',
    summary: 'Bessemer City Schools announced a new partnership with three local businesses to provide funding for after-school tutoring and enrichment programs.',
    link: 'https://www.bessemer.k12.al.us/news/partnership',
    notes: 'Follow up on program launch in April',
    canary_score: 8.9,
    source_category: 'News',
    perch_tag: 'Community',
  },
  {
    id: 10,
    date: '2026-02-28',
    headline: 'Annual Science Fair Showcases Student Innovation',
    summary: 'More than 150 students participated in this year\'s district-wide science fair, with projects ranging from renewable energy to AI-assisted learning tools.',
    link: 'https://www.instagram.com/p/DW-sciencefair/',
    notes: null,
    canary_score: 8.4,
    source_category: 'Social Media',
    perch_tag: 'STEM',
  },
];

export const mockQueries = [
  { id: 1, query: 'Abrams Elementary School Bessemer', created_at: '2026-01-15', status: 'active' },
  { id: 2, query: 'Bessemer City Board of Education', created_at: '2026-01-15', status: 'active' },
  { id: 3, query: 'Bessemer City Board of Education policy decision', created_at: '2026-01-20', status: 'active' },
  { id: 4, query: 'Bessemer City High School', created_at: '2026-01-15', status: 'active' },
  { id: 5, query: 'Bessemer City High School Abrams Elementary news', created_at: '2026-02-01', status: 'active' },
  { id: 6, query: 'Bessemer City Schools enrollment', created_at: '2026-02-10', status: 'active' },
  { id: 7, query: 'Bessemer City Schools STEM program', created_at: '2026-02-15', status: 'active' },
];

export const mockNotes = [
  {
    id: 1,
    article_id: 3,
    article_headline: 'Attendance is Important! Showing up every day makes a BIG difference!',
    content: 'Testing this right now',
    created_at: '2026-03-21T14:30:00',
    author: 'Admin',
  },
  {
    id: 2,
    article_id: 6,
    article_headline: 'Board of Education Approves New STEM Curriculum for Elementary Schools',
    content: 'Important policy decision - track follow-up coverage',
    created_at: '2026-03-10T09:15:00',
    author: 'Admin',
  },
  {
    id: 3,
    article_id: 9,
    article_headline: 'New Partnership with Local Business to Fund After-School Programs',
    content: 'Follow up on program launch in April',
    created_at: '2026-03-01T16:45:00',
    author: 'Admin',
  },
];

// Chart data
export const mockMentionTrend = [
  { date: 'Feb 1', mentions: 3 },
  { date: 'Feb 8', mentions: 5 },
  { date: 'Feb 15', mentions: 4 },
  { date: 'Feb 22', mentions: 7 },
  { date: 'Mar 1', mentions: 8 },
  { date: 'Mar 8', mentions: 6 },
  { date: 'Mar 15', mentions: 9 },
  { date: 'Mar 22', mentions: 12 },
  { date: 'Mar 29', mentions: 5 },
  { date: 'Apr 2', mentions: 3 },
];

export const mockSourceBreakdown = [
  { name: 'Social Media', value: 55, color: '#3B82F6' },
  { name: 'News', value: 30, color: '#F5C518' },
  { name: 'Blog', value: 10, color: '#22C55E' },
  { name: 'Other', value: 5, color: '#94A3B8' },
];

export const mockSentimentTrend = [
  { date: 'Feb 1', score: 7.2 },
  { date: 'Feb 8', score: 7.8 },
  { date: 'Feb 15', score: 8.1 },
  { date: 'Feb 22', score: 7.5 },
  { date: 'Mar 1', score: 8.3 },
  { date: 'Mar 8', score: 8.8 },
  { date: 'Mar 15', score: 8.5 },
  { date: 'Mar 22', score: 8.7 },
  { date: 'Mar 29', score: 9.0 },
  { date: 'Apr 2', score: 8.75 },
];
