'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { claimSocialAffiliate, revokeSocialAffiliate } from '@/app/actions';
const TYPES=[['school','School'],['athletics','Athletics'],['fine_arts','Fine arts'],['cte','CTE'],['club','Club'],['booster','Booster'],['foundation','Foundation'],['pto_pta','PTO / PTA'],['program','Program'],['other','Other']];
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const number=v=>new Intl.NumberFormat('en-US').format(Number(v)||0);
const date=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(v)):'No exact-author history';
export default function AffiliateAccountsClient({districtId,districtName,districts=[],accounts=[],claims=[],previews=[]}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [error,setError]=useState('');const [message,setMessage]=useState('');
 const eligible=accounts.filter(a=>(a.platform_account_id||String(a.handle||'').replace(/^@+/,''))&&!claims.some(c=>c.status==='active'&&c.social_account_id===a.id));
 const [form,setForm]=useState({socialAccountId:'',affiliateType:'school',relationshipLabel:'',verificationSource:'district',verificationNote:''});
 function navigate(value){router.push(value?`/dashboard/affiliates?districtId=${encodeURIComponent(value)}`:'/dashboard/affiliates');}
 function submit(e){e.preventDefault();setError('');setMessage('');startTransition(async()=>{try{await claimSocialAffiliate({...form,districtId,idempotencyKey:crypto.randomUUID()});setForm({socialAccountId:'',affiliateType:'school',relationshipLabel:'',verificationSource:'district',verificationNote:''});setMessage('Affiliate claim saved. No Social records or collection settings changed.');router.refresh();}catch(err){setError(err?.message||'Unable to save affiliate claim.');}});}
 function revoke(claim){const reason=window.prompt('Why is this affiliate claim being revoked?');if(!reason?.trim())return;setError('');setMessage('');startTransition(async()=>{try{await revokeSocialAffiliate({districtId,affiliateClaimId:claim.id,expectedVersion:claim.claim_version,revocationReason:reason,idempotencyKey:crypto.randomUUID()});setMessage('Affiliate claim revoked. Existing Social records were not changed.');router.refresh();}catch(err){setError(err?.message||'Unable to revoke affiliate claim.');}});}
 return <main className="affiliate-admin-page"><header><a href="/dashboard">← Dashboard</a><span>Canary administrator</span><h1>District-claimed affiliates</h1><p>Verify exact accounts in a district communications ecosystem without classifying them as central-district controlled.</p></header>
 <label className="affiliate-district-selector"><span>District</span><select value={districtId||''} onChange={e=>navigate(e.target.value)}><option value="">Choose a district</option>{districts.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
 {!districtId?<section className="affiliate-admin-panel"><p>Choose one district before reading or changing affiliate claims.</p></section>:<>
 <section className="affiliate-admin-panel"><h2>{districtName}</h2><p>A claim requires a configured exact account ID or normalized handle. It does not start collection or reclassify existing posts.</p><form className="social-affiliate-form" onSubmit={submit}>
 <label><span>Configured account</span><select required value={form.socialAccountId} onChange={e=>setForm({...form,socialAccountId:e.target.value})}><option value="">Choose exact account</option>{eligible.map(a=><option key={a.id} value={a.id}>{a.display_name||a.handle||a.platform_account_id} · {label(a.platform)} · {a.active?'Collection enabled':'Registry only'}</option>)}</select></label>
 <label><span>Affiliate type</span><select value={form.affiliateType} onChange={e=>setForm({...form,affiliateType:e.target.value})}>{TYPES.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
 <label><span>Relationship label</span><input required maxLength={120} value={form.relationshipLabel} onChange={e=>setForm({...form,relationshipLabel:e.target.value})} placeholder="District high school athletics"/></label>
 <label><span>Verification source</span><select value={form.verificationSource} onChange={e=>setForm({...form,verificationSource:e.target.value})}><option value="district">District confirmation</option><option value="official_website">Official website</option><option value="canary_admin">Canary administrator</option></select></label>
 <label className="social-affiliate-note"><span>Verification note</span><textarea maxLength={2000} value={form.verificationNote} onChange={e=>setForm({...form,verificationNote:e.target.value})} placeholder="Who verified the exact account, where, and when?"/></label><div className="social-affiliate-submit"><button className="btn btn-primary" disabled={pending||!eligible.length}>{pending?'Saving…':'Claim affiliate account'}</button></div></form>
 {error&&<p className="social-affiliate-message error" role="alert">{error}</p>}{message&&<p className="social-affiliate-message success" role="status">{message}</p>}</section>
 <section className="affiliate-admin-panel affiliate-preview-panel"><div className="affiliate-preview-heading"><div><span>Read-only model</span><h2>Historical attribution preview</h2><p>Exact platform and normalized author-handle matches only. This preview does not update stored posts, collection settings, or client reporting.</p></div><strong>0 writes</strong></div>
 <div className="affiliate-preview-list">{!previews.length?<p>No active affiliate claim is available to preview.</p>:previews.map(p=><article key={p.claimId}><header><div><strong>{p.relationshipLabel}</strong><span>{p.account.displayName||p.account.handle} · {label(p.account.platform)} · @{p.account.handle}</span></div><small>{p.matchedPosts?`${number(p.matchedPosts)} exact-author posts`:'Identity verified · no historical exact-author records'}</small></header>
 <div className="affiliate-preview-metrics"><div><span>Modeled affiliate posts</span><strong>{number(p.modeledAffiliatePosts)}</strong></div><div><span>Recorded engagement</span><strong>{number(p.engagementTotal)}</strong></div><div><span>Last 90 days</span><strong>{number(p.last90Days)}</strong></div><div><span>Current visibility</span><strong>{number(p.activePosts)} active · {number(p.excludedPosts)} excluded</strong></div></div>
 <p className="affiliate-preview-rule">Exact match: {label(p.account.platform)} + normalized author handle <code>@{p.account.handle}</code>. Stored rows changed: No.</p>
 {p.matchedPosts?<><div className="affiliate-preview-breakdown"><span>Current classifications</span>{Object.entries(p.relationships).map(([key,value])=><small key={key}>{label(key)}: {number(value)}</small>)}<small>History: {date(p.firstPublishedAt)} to {date(p.latestPublishedAt)}</small></div><div className="affiliate-preview-samples">{p.samples.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer"><strong>{String(s.headline||'Social post').slice(0,140)}</strong><span>{date(s.publishedAt)} · {label(s.relationshipType)} · {label(s.visibilityStatus)} · {number(s.engagementTotal)} engagements</span></a>)}</div></>:<p className="affiliate-preview-empty">Canary has not historically stored posts authored by this exact account. Keep the verified identity in the registry; do not infer attribution from names, mentions, or similar handles.</p>}</article>)}</div></section>
 <section className="affiliate-admin-panel"><h2>Claim history</h2><div className="affiliate-claim-list">{!claims.length?<p>No claims recorded for this district.</p>:claims.map(c=>{const a=c.social_accounts||{};return <article key={c.id}><div><strong>{c.relationship_label}</strong><span>{a.display_name||a.handle||a.platform_account_id} · {label(a.platform)} · {label(c.affiliate_type)}</span><small>{label(c.status)} · {a.active?'Collection enabled':'Registry only'} · verified via {label(c.verification_source)} · version {c.claim_version}</small></div>{c.status==='active'&&<button className="btn btn-secondary" disabled={pending} onClick={()=>revoke(c)}>Revoke</button>}</article>;})}</div></section></>}</main>;
}
